### PR TITLE
short-hand for triggering `.valueOf()`

### PR DESCRIPTION
**Pull request by deveedutta**

### CODE REVIEW

**Comment by caiogondim** [comment]
Care to submit a PR?

**Comment by deveedutta** [comment]
I'm sorry, but isn't this a PR already? Or, do I need to do something else?

**Comment by caiogondim** [comment]
It is, sorry.

**Comment by caiogondim** [comment]
Will have to decline this one since the code is more "magical" on your PR.
I like to have an explicit code.

**Pull request closed without merging**
