### PR TITLE
Added AMD module snippet

### PR DESCRIPTION
**Pull request by brunano21**
Added the AMD module snippet. 
Feel free to review and comment.

### CODE REVIEW

**Comment by caiogondim** [comment]
That is fantastic.
I will just add a README section to it.

Cheers.

**Comment by brunano21** [comment]
Oh sorry, I forgot to add it to the README.

**Comment by caiogondim** [comment]
On the snippet when you say `privateMethod`, wouldn't it be more accurate to call it static, since it public available but don't need to be instantiated to be used?

**Comment by caiogondim** [comment]
BTW, the README section was added.

**Comment by brunano21** [comment]
You're right! 
Have a look to this. 

https://gist.github.com/jonnyreeves/2474026

I may add the 'real' private methods too

**Comment by caiogondim** [comment]
That would be awesome =)

**Pull request merged**
